### ISSUE TITLE
Add time stamp to all the data visualizations

### ISSUE THREAD

**Issue by iobik** [soichih/apred#38]
Add timestamp to all the data sources - to provide users with information about the currency of our data/visualization.

**Comment by soichih** [comment]
All data is cached from statsamerica DB once a day. I believe DR is updated once a week(?) at statsamerica end, and same for storm history. Most other data is more / less computed once (static) and doesn't get updated. Would it be enough to mention that, or do we need more detail? If so, can you list which page/item should have which information?

By the way, I suggest creating a page under our CMS site and host all data source information there instead of storing this on the platform itself. For example > https://eri.iu.edu/tools-and-resources/data-resources.html

**Comment by iobik** [comment]
Ok. I'll share a prototype that highlights where to add time stamps. Thank you!
