### ISSUE TITLE
Integrate with an authentication service

### ISSUE THREAD

**Issue by ljpaul** [soichih/apred#53]
EDA uses a local AD, so we will be unable to access it. They said that a local authentication in our app would be good and collecting basic demographic information and justification for users (if we can) is a good idea.

**Comment by soichih** [comment]
I started configuring the auth service.. I am still waiting on oauth2 registration for orcid.. but it can be tested now

> https://api.ctil.iu.edu/auth/
![image](https://user-images.githubusercontent.com/923896/97497917-a95dd680-1941-11eb-8cb7-f4a5d673b19f.png)

There is also an account settings page
> https://api.ctil.iu.edu/auth/#!/settings/account
this can be used to associate other orcid accounts

I will work on receiving the jwt token issued by the auth service by APRED next.

**Comment by soichih** [comment]
I've released the update that would allow users to register / login through some auth buttons.

![image](https://user-images.githubusercontent.com/923896/98037318-612f3000-1de9-11eb-84aa-103947bed81d.png)

The eligibility button will only show up if users are logged in.

![image](https://user-images.githubusercontent.com/923896/98037365-7015e280-1de9-11eb-9a35-b55e0fe0bfb5.png)

In the future, we could update this so that only the users with certain access roll (maybe like "EDA"?) can see these buttons.

**Comment by iobik** [comment]
Thank you for your work on this! @soichih
