### ISSUE TITLE
Do not show business sectors that do not contain any information

### ISSUE THREAD

**Issue by iobik** [soichih/apred#85]
Please, do not show business sectors that do not contain any information to make the page look cleaner and less distraction. It appears like something is broken when there is no data but, that's not the case.

![image](https://user-images.githubusercontent.com/71714873/107136527-2b12b800-68d2-11eb-9b9b-dd9e7a646561.png)

**Comment by soichih** [comment]
This was happening because the Dyer county actually contains a single value (for 2016) but due to a bug in my graph code it was not displaying. I am thinking about switching to plotly graph (See #84).

Should I hide a graph with data from only 1 year?

![image](https://user-images.githubusercontent.com/923896/107171115-fa915380-698f-11eb-985f-9e316e6a043f.png)

Or should we leave it like this and ask @ljpaul if the data can be corrected to include all years?

**Comment by ljpaul** [comment]
@soichih Let's display zero if the data is missing. There are no values in the table for `FIPS 47045` and `NAICS 22` which, I believe, means that there is no employment or establishments.

The following query returned no results which, I think, validates my hypothesis.

`SELECT * FROM [stats4].[dbo].[cbp_uscnty] WHERE [estab_total] = 0.0 AND [mm_employees] = 0.0`

**Comment by soichih** [comment]
By displaying zero, do you mean to show x values for all year ranges (2012-2018) regardless of if there is a data or not?

**Comment by iobik** [comment]
@soichih @ljpaul Where are we on resolving this issue?

**Comment by ljpaul** [comment]
That is what I was thinking!

**Comment by iobik** [comment]
@soichih Please can you confirm the status of this issue?

**Comment by soichih** [comment]
I believe this was handled as part of another issue. The Dyer county now shows 0(empty) record for all years between 2012 and 2019.

![image](https://user-images.githubusercontent.com/923896/116278932-f5ed6780-a754-11eb-89c3-7ccdc054c04c.png)

**Comment by ljpaul** [comment]
Closing as a dupe.
